spring.application.name=resepti

spring.datasource.url=jdbc:postgresql://localhost:5432/recipedb
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=arsi
spring.datasource.password=salasana

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# #H2-terminaali
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# #H2-tietokannan osoite
# spring.datasource.url=jdbc:h2:mem:resepti

# #Näytä tietokantaan kohdistuvat toimenpiteet terminaalissa
# spring.jpa.show-sql=true