CREATE TABLE kayttaja (
    kayttaja_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kayttajatunnus VARCHAR(255) NOT NULL UNIQUE,
    salasana_hashed VARCHAR(255) NOT NULL,
    rooli VARCHAR(255) NOT NULL,

    PRIMARY KEY (kayttaja_id)
);

CREATE TABLE resepti (
    resepti_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nimi VARCHAR(50) NOT NULL UNIQUE,
    kuvaus VARCHAR(100),
    ohje TEXT NOT NULL,
    valmistusaika INTEGER NOT NULL,
    annosmaara INTEGER NOT NULL,
  
    PRIMARY KEY (resepti_id),
    CONSTRAINT chk_valmistusaika CHECK (valmistusaika <= 1440),
    CONSTRAINT chk_annosmaara CHECK (annosmaara >= 1)
);

CREATE TABLE tag (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nimi VARCHAR(255) NOT NULL UNIQUE,

    PRIMARY KEY (tag_id)
);

CREATE TABLE ainesosa (
    ainesosa_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nimi VARCHAR(255) NOT NULL UNIQUE,

    PRIMARY KEY (ainesosa_id)
);

CREATE TABLE resepti_tag (
    resepti_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    PRIMARY KEY (resepti_id, tag_id),
    CONSTRAINT fk_resepti_tag_resepti
        FOREIGN KEY (resepti_id)
        REFERENCES resepti(resepti_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_resepti_tag_tag
        FOREIGN KEY (tag_id)
        REFERENCES tag(tag_id)
        ON DELETE CASCADE
);

CREATE TABLE resepti_aines (
    resepti_aines_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resepti_id BIGINT NOT NULL,
    ainesosa_id BIGINT NOT NULL,
    maara DOUBLE PRECISION,
    yksikko VARCHAR(255),

    PRIMARY KEY (resepti_aines_id),
    CONSTRAINT fk_resepti_aines_resepti
        FOREIGN KEY (resepti_id)
        REFERENCES resepti(resepti_id),
    CONSTRAINT fk_resepti_aines_ainesosa
        FOREIGN KEY (ainesosa_id)
        REFERENCES ainesosa(ainesosa_id)
);


